version: '3.8'

services:
  snmp-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snmpv3_telemetry_agent
    restart: unless-stopped
    ports:
      - "10161:10161/udp"
      - "8000:8000"
    volumes:
      - ./incoming_reports:/app/incoming_reports
    environment:
      - PYTHONUNBUFFERED=1